#!/bin/zsh

export DOTFILES_ROOT=${DOTFILES_ROOT:-"$HOME/github/my_dot_files"}
source ${DOTFILES_ROOT}/my_shell_config.sh

case $1 in
    wechat)
    chrome "https://mp.weixin.qq.com/...";;
    bbs)
    chrome "https://bbs.byr.cn/#!board/JobInfo";;
    qisi)
    chrome "https://news.miracleplus.com/";;
    map)
    chrome "https://ditu.amap.com/...";;
    *)
    echo "Usage: goto <wechat|bbs|qisi|map>"
    echo "Available targets:"
    echo "  wechat  - 微信公众号后台"
    echo "  bbs     - 北邮人论坛"
    echo "  qisi    - 奇绩创坛"
    echo "  map     - 高德地图"
    ;;
esac

